config/routes.rb
JobApp::Application.routes.draw do
  authenticated :user do
    root :to => 'marketing#employees'
  end
  root :to => 'marketing#employees'

  devise_for :users, skip: [:registrations]
  devise_for :employees, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}
  devise_for :employers, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}

  post "/avatar", to: "employees/resumes#avatar"
  namespace :employees do
  	resource :resume, only: ["edit", "update"]
    resources :applieds, only: ["create"]
  end
  resources :employees, only: ["show"]

  resources :listings, only: ["index", "show"]
  get '/employers', :to => 'marketing#employers'
  namespace :employers do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    get '/dashboard/potential_hires', to: 'potential_hires#index', as: :potential_hires
    resources :jobs, except: ['index', "show"]
  end


  #review namespace for ranking users
  namespace :admin do
    resources :reviews, only: ["index", "edit", "update"]
    resources :feedbacks, only: ['index']
    resources :stats, only: ['index']
  end

  get '/about_us', to: 'marketing#about_us'
  get '/contact', to: 'admin/feedbacks#new'
  post '/contact', to: 'admin/feedbacks#create'

  resources :charges, only: ['create']
end

app/models/employee.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string(255)
#  last_name              :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  type                   :string(255)
#  reviewed               :boolean
#  score                  :integer
#  company_name           :string(255)
#  can_contact            :boolean          default(FALSE)
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#

class Employee < User
	attr_protected :reviewed, :score
	has_one :resume
	has_many :applieds
  has_many :applied_jobs, :through => :applieds, :source => :job

  attr_accessible :can_contact

  after_create :create_resume
  before_create :can_contact_default

  validate :needs_score_on_review

  def can_contact?
    can_contact
  end

  def applied_for? job
    job.applicants.each do |applicant|
      return true if applicant == self
    end
    false
  end

  private
    def can_contact_default
      self.can_contact = true
    end

  	def create_resume
      self.build_resume.save if self.resume.nil?
  	end

  	def needs_score_on_review
  		if self.reviewed
  			errors.add(:score, 'Not a valid score!') unless
          self.score && self.score >= 0 && self.score <= 100
  		end
		end
end

app/models/resume.rb
# == Schema Information
#
# Table name: resumes
#
#  id                :integer          not null, primary key
#  phone_number      :string(255)
#  address           :string(255)
#  job_experience    :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  employee_id       :integer
#  city              :string(255)
#  state             :string(255)
#  zipcode           :string(255)
#  description       :text
#  birthday          :date
#  highest_education :string(255)
#  highest_major     :string(255)
#  current_education :string(255)
#  current_major     :string(255)
#  graduation_date   :date
#

class Resume < ActiveRecord::Base
  attr_accessible :address, :city, :state, :zipcode,
   	:phone_number, :job_experiences_attributes, :description,
   	:highest_education, :highest_major,
   	:current_education, :current_major,
   	:graduation_date, :birthday, :references_attributes

  belongs_to :employee
  has_many :job_experiences
  has_many :references
  accepts_nested_attributes_for :job_experiences, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :references, :reject_if => :all_blank, :allow_destroy => true

  validates :phone_number, format: { with: /\A\d{3}-?\d{3}-?\d{4}\z/ }, allow_blank: true

  before_save :needs_review?

  def full_address
    if !address.blank? && !city.blank? && !state.blank? && !zipcode.blank?
      "#{address}, #{city}, #{state}, #{zipcode}"
    else
      "No address entered."
    end
  end

  def incomplete?
    address.blank? || city.blank? || state.blank? || zipcode.blank? ||
     phone_number.blank? || description.blank? || birthday.blank?
  end

  private

    def needs_review?
      if self.changed? && self.employee
        e = self.employee
        e.reviewed = nil;
        e.save
      end
    end

end

app/controllers/employee/applieds_controller.rb
class Employee::AppliedsController < ApplicationController
  # POST /applieds
  # POST /applieds.json
  def create
    params[:applied][:employee_id] = current_user.id if current_user.employee?
    @applied = Applied.new(params[:applied])

    respond_to do |format|
      if @applied.save
        format.html { render json: @applied, status: :created }
        format.json { render json: @applied, status: :created }
      else
        format.html { render json: @applied.errors, status: :unprocessable_entity }
        format.json { render json: @applied.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applieds/1
  # DELETE /applieds/1.json
  def destroy
    @applied = Applied.find(params[:id])
    @applied.destroy

    respond_to do |format|
      format.html { redirect_to applieds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/employee/resumes_controller.rb
class Employee::ResumesController < ApplicationController
  authorize_resource :resume
  before_filter :employee_only!

  # GET /resumes/1/edit
  def edit
    @resume = resume
    @resume.job_experiences.build unless !@resume.job_experiences.empty?
    @resume.references.build unless !@resume.references.empty?
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = resume
    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to root_path, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /avatar
  def avatar
    if params[:employee] && current_user.update_attributes(params[:employee])
      flash[:notice] = "Avatar successfully updated."
    else
      flash[:error] = "Avatar could not be updated."
    end
    redirect_to edit_employee_resume_path
  end

  private
    def resume
      return @resume || current_user.resume || current_user.build_resume
    end
end

app/controllers/employees/applieds_controller.rb
class Employees::AppliedsController < ApplicationController
  # POST /applieds
  # POST /applieds.json
  def create
    params[:applied][:employee_id] = current_user.id if current_user.employee?
    @applied = Applied.new(params[:applied])

    respond_to do |format|
      if @applied.save
        format.html { render json: @applied, status: :created }
        format.json { render json: @applied, status: :created }
      else
        format.html { render json: @applied.errors, status: :unprocessable_entity }
        format.json { render json: @applied.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/employees/resumes_controller.rb
class Employees::ResumesController < ApplicationController
  authorize_resource :resume
  before_filter :employee_only!

  # GET /resumes/1/edit
  def edit
    @resume = resume
    @resume.job_experiences.build unless !@resume.job_experiences.empty?
    @resume.references.build unless !@resume.references.empty?
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = resume
    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to listings_path, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /avatar
  def avatar
    if params[:employee] && current_user.update_attributes(params[:employee])
      #if params[:employee][:avatar].blank?
        flash[:notice] = "Avatar successfully updated."
        redirect_to edit_employees_resume_path
      #else
      #  flash[:notice] = "Crop your avatar."
      #  render "crop"
      #end
    else
      flash[:error] = "Avatar could not be updated."
      redirect_to edit_employees_resume_path
    end

  end

  private
    def resume
      return @resume || current_user.resume || current_user.build_resume
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  authorize_resource :resume
  before_filter :employee_only!

  # GET /resumes/1/edit
  def edit
    @resume = resume
    @resume.job_experiences.build unless !@resume.job_experiences.empty?
    @resume.references.build unless !@resume.references.empty?
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = resume
    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to root_path, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /avatar
  def avatar
    if params[:employee] && current_user.update_attributes(params[:employee])
      flash[:notice] = "Avatar successfully updated."
    else
      flash[:error] = "Avatar could not be updated."
    end
    redirect_to edit_employee_resume_path
  end

  private
    def resume
      return @resume || current_user.resume || current_user.build_resume
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper

end

app/views/employees/resumes/_form.html.haml
= simple_form_for(@resume, url: employees_resume_path, html: {method: :put}) do |f|
	.errors
		= f.error_notification
	.avatar.pull-right.text-right
		= image_tag current_user.avatar_url
		%br
		= link_to "Upload avatar from computer", "#", id: "upload-avatar"
		%br
		= link_to "Change image with gravatar", "https://en.gravatar.com/"

	.form-inputs

		= f.input :address
		= f.input :city
		= f.input :state, collection: us_states, as: :select
		= f.input :zipcode
		= f.input :phone_number, label: "Phone Number"
		= f.input :birthday, start_year: Date.today.year - 90

		= f.input :highest_education, label: "Highest Education Completed" do
			= f.input_field :highest_education, label: "Highest Education Completed",collection: ["High School", "College"]
			= f.input_field :highest_major, placeholder: "Major (If applicable)"

		= f.input :current_education, label: "Current Education (If Applicable)" do
			= f.input_field :current_education, label: "Curent Education (If applicable)",collection: ["High School", "College"]
			= f.input_field :current_major, placeholder: "Major (If applicable)"


		= f.input :graduation_date, label: "Graduation Date (For Current Education)", start_year: Date.today.year - 90
		= f.input :description, input_html: { class: "span9", rows: 10 }, placeholder: "Tell us about yourself!"
		%p Job Experience
		= f.simple_fields_for :job_experiences do |builder|
			= render "job_experience_fields", f: builder
		.links
			= link_to_add_association '+ Add more job experience', f, :job_experiences
		%br
		%p References (3 Recommended)
		= f.simple_fields_for :references do |builder|
			= render "reference_fields", f: builder
		.links
			= link_to_add_association '+ Add more references', f, :references

	.form-actions
		= f.button :submit, value: "Update Resume", class: "btn btn-success"

app/views/employees/resumes/_job_experience_fields.html.haml
.nested-fields
	= f.input_field :title, label: false, placeholder: "Title"
	= f.input_field :company, label: false, placeholder: "Company"
	= f.input_field :time, label: false, as: :select, collection: time_frames_short
	= link_to_remove_association "Remove", f

app/views/employees/resumes/_reference_fields.html.haml
.nested-fields
  = f.input_field :name, label: false, placeholder: "Name"
  = f.input_field :relationship, label: false, placeholder: "Relationship"
  = f.input_field :length_known, label: false, placeholder: "Length Known", as: :select, collection: time_frames_long
  %br
  = f.input_field :phone_number, label: false, placeholder: "Phone Number"
  = f.input_field :email, label: false, placeholder: "Email Address"
  = link_to_remove_association "Remove", f
%br

app/views/employees/resumes/crop.html.haml
- content_for :title, "Crop Avatar"
%h1 Crop Your Avatar
%br
.text-center
  = image_tag current_user.avatar.url(:large), id: "cropbox", data: { ratio: current_user.avatar_geometry(:original).width / current_user.avatar_geometry(:large).width}
%hr
= simple_form_for(current_user, url: avatar_path, method: :post) do |f|
  - for attribute in [:crop_x, :crop_y, :crop_w, :crop_h]
    = f.hidden_field attribute, :id => attribute
  = f.submit "Crop", class: "btn btn-primary pull-right"

app/views/employees/resumes/edit.html.haml
- content_for :title, "Resume"
%h1 My Resume
= render 'form'

#my-modal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  = simple_form_for current_user, url: avatar_path, html: {multipart: true}, method: :post do |f|
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h3 Upload Avatar
    .modal-body
      = f.input :avatar, as: :file
    .modal-footer
      %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
      %button.btn.btn-primary Upload