config/routes.rb
JobApp::Application.routes.draw do
  authenticated :user do
    root :to => 'marketing#employees'
  end
  root :to => 'marketing#employees'

  devise_for :users, skip: [:registrations]
  devise_for :employees, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}
  devise_for :employers, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}

  post "/avatar", to: "employees/resumes#avatar"
  namespace :employees do
  	resource :resume, only: ["edit", "update"]
    resources :applieds, only: ["create"]
  end
  resources :employees, only: ["show"]

  resources :listings, only: ["index", "show"]
  get '/employers', :to => 'marketing#employers'
  namespace :employers do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    get '/dashboard/potential_hires', to: 'potential_hires#index', as: :potential_hires
    resources :jobs, except: ['index', "show"]
  end


  #review namespace for ranking users
  namespace :admin do
    resources :reviews, only: ["index", "edit", "update"]
    resources :feedbacks, only: ['index']
    resources :stats, only: ['index']
  end

  get '/about_us', to: 'marketing#about_us'
  get '/contact', to: 'admin/feedbacks#new'
  post '/contact', to: 'admin/feedbacks#create'

  resources :charges, only: ['create']
end

app/controllers/listings_controller.rb
# JobsController is for employers, ListingsController is for all.
class ListingsController < ApplicationController
  before_filter :authenticate_user!

  def index

    if !valid_zipcode? params[:zipcode]
      @listings = Job.search(params[:search], ip_zipcode, params[:dist])
    else
      @listings = Job.search(params[:search], params[:zipcode], params[:dist])
    end

    @coords = coords @listings

    if params[:map] == "true"
      @near = near_formatted @listings
      render "map"
    else
      @listings = @listings.paginate(page: params[:page]).includes(:employer, :applicants)
    end
  end

  def show
  	@listing = Job.find(params[:id])
  end

  private

    def valid_zipcode? zipcode
      params[:zipcode] && !params[:zipcode].empty? && Job.is_number?(params[:zipcode])
    end

    def near_formatted n
      return n.map do |near|
        {title: near.title, coords: [near.latitude, near.longitude],
          url: listing_path(near), company_name: near.employer.company_name}
      end
    end

    def coords listings
      c = Geocoder::Calculations.geographic_center(listings.map{ |l| [l.latitude, l.longitude]})
      if c[0].nan?
        if valid_zipcode? params[:zipcode]
          c = Geocoder.coordinates(params[:zipcode])
        else
          c = Geocoder.coordinates(ip_zipcode)
        end
      end

      return c || Geocoder::BACKUP_LOCATION
    end

    def ip_zipcode
      if Rails.env.production?
        request.location.postal_code
      else
        return "65714"
      end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper

end

app/views/listings/index.html.haml
- content_for :title, "Job Listings"
.row
  .span4
    %h1 Listings
    %p
      = @listings.count
      Listings Available
    %p
      Views:
      = link_to "Listings", params.merge(map: false), class: "disabled-link"
      |
      = link_to "Map", params.merge(map: true)
  .span8
    = form_tag listings_path, method: :get, class: "form-inline pull-right search-form" do
      = hidden_field_tag :map, params[:map] || false
      = text_field_tag :search, params[:search], class: "input-medium", placeholder: "Search Jobs"
      Within
      = select_tag :dist, options_for_select(distances, params[:dist]), class: "input-medium"
      Of
      = text_field_tag :zipcode, params[:zipcode], class: "input-mini", placeholder: "Zipcode"
      = submit_tag "Search", class: "btn btn-primary", name: nil

= will_paginate @listings, renderer: BootstrapPagination::Rails
%hr
- if @listings.empty?
  %p
    There aren't any jobs here.
- else
  - @listings.each do |listing|
    .row
      .span10
        %h4= link_to listing.title, listing_path(listing)
        .row-fluid
          .span4
            %p= listing.employer.company_name
          .span4
            %p
              Pay:
              = number_to_currency listing.pay
          .span4
            %p
              = "#{listing.city}, #{listing.state}"
              -#(hardcoded, not an attribute yet
        %p= truncate listing.description, length: 100
      .span2
        - if current_user.employee?
          - if current_user.applied_for? listing
            = link_to "Applied!", "#", class: "btn btn-success btn-apply pull-right", data: {job: listing.id}
          - else
            = link_to "Apply", "#", class: "btn btn-info btn-apply pull-right", data: {job: listing.id}
    %hr

= will_paginate @listings, renderer: BootstrapPagination::Rails

app/views/listings/map.html.haml
- content_for :title, "Map | Job Listings"
#map-search-form.higher.well.border.well-small
  = form_tag listings_path, method: :get, class: "form-inline pull-right search-form search-form-absolute" do
    = link_to "Back", params.merge(map: false), class: "btn btn-warning"
    = hidden_field_tag :map, params[:map] || false
    = text_field_tag :search, params[:search], class: "input-medium", placeholder: "Search Jobs"
    Within
    = select_tag :dist, options_for_select(distances, params[:dist]), class: "input-medium"
    Of
    = text_field_tag :zipcode, params[:zipcode], class: "input-mini", placeholder: "Zipcode"
    = submit_tag "Search", class: "btn btn-primary", name: nil

#map-canvas.absolute.full-screen{:data => {lat: @coords[0], long: @coords[1], near: @near.to_json}}

app/views/listings/show.html.haml
- content_for :title, "#{@listing.title} | Job Listings"
%h1= @listing.title
- if current_user.employer? && current_user.my_listing?(@listing)
  .row
    .span12
      = link_to "Edit Listing", edit_employers_job_path(@listing), class: "btn btn-info"
      = link_to "Applicants", "#", class: "btn btn-warning btn-applicants"
- if current_user.employee?
  - if current_user.applied_for? @listing
    %br
    = link_to "Applied!", "#", id: "btn-apply",class: "btn btn-success btn-skinny", data: {job: @listing.id}
  - else
    = link_to "Apply", "#", id: "btn-apply", class: "btn btn-info btn-skinny", data: {job: @listing.id}
.row
  .span3
    %h4 Employer
    %p= @listing.employer.company_name
  .span2
    %h4 Pay
    %p= number_to_currency @listing.pay
  .span4
    %h4 Location
    %p= @listing.full_address
%h4 Job Description
%p= @listing.description
%hr

.row
  .span12
    #map-canvas{:data => {lat: @listing.latitude, long: @listing.longitude, title: @listing.employer.company_name}}

%hr
.row
  .span12
    - if current_user.employer? && current_user.my_listing?(@listing)
      %h3.applicants Applicants
      - if @listing.applicants.count > 0
        %p
          Need more options?
          = link_to "Find potential employees!", employers_potential_hires_path, class: "btn btn-success"
        %table.table.table-striped.table-bordered.table-hover
          %thead
            %tr
              %th Name
              %th Other Info
              %th Score
          %tbody
            - @listing.applicants.each do |applicant|
              %tr
                %td= link_to applicant.full_name, employee_path(applicant)
                %td= applicant.resume.description ? truncate(applicant.resume.description, length: 100) : "No Description"
                %td= applicant.score ? applicant.score : "No Score"
      - else
        %p
          No one has applied yet.
          = link_to "Find potential employees!", employers_potential_hires_path, class: "btn btn-success"
    - else
      %h3
        Other Listings By This Employer
      - if @listing.employer.jobs.count > 1
        - @listing.employer.jobs.take(5).each do |listing|
          - if listing == @listing
            - next
          .row
            .span12
              %h4= link_to listing.title, listing_path(listing)
              .row-fluid
                .span4
                  %p= listing.employer.company_name
                .span4
                  %p
                    Pay:
                    = number_to_currency listing.pay
                .span4
                  %p
                    = "#{listing.city}, #{listing.state}"
                    -#(hardcoded, not an attribute yet
              %p= truncate listing.description, length: 100
      - else
        %p The employer doesn't have anymore listings