config/routes.rb
JobApp::Application.routes.draw do
  authenticated :user do
    root :to => 'marketing#employees'
  end
  root :to => 'marketing#employees'

  devise_for :users, skip: [:registrations]
  devise_for :employees, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}
  devise_for :employers, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}

  post "/avatar", to: "employees/resumes#avatar"
  namespace :employees do
  	resource :resume, only: ["edit", "update"]
    resources :applieds, only: ["create"]
  end
  resources :employees, only: ["show"]

  resources :listings, only: ["index", "show"]
  get '/employers', :to => 'marketing#employers'
  namespace :employers do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    get '/dashboard/potential_hires', to: 'potential_hires#index', as: :potential_hires
    resources :jobs, except: ['index', "show"]
  end


  #review namespace for ranking users
  namespace :admin do
    resources :reviews, only: ["index", "edit", "update"]
    resources :feedbacks, only: ['index']
    resources :stats, only: ['index']
  end

  get '/about_us', to: 'marketing#about_us'
  get '/contact', to: 'admin/feedbacks#new'
  post '/contact', to: 'admin/feedbacks#create'

  resources :charges, only: ['create']
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_filter :admin_only!
  # GET /admin/reviews
  # GET /admin/reviews.json
  def index
    @reviews = Employee.where(reviewed: nil)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /admin/reviews/1/edit
  def edit
    @review = Employee.find(params[:id])
  end

  # PUT /admin/reviews/1
  # PUT /admin/reviews/1.json
  def update
    @review = Employee.find(params[:id])

    respond_to do |format|
      @review.reviewed = true; @review.score = params[:employee][:score];
      if @review.save
        format.html { redirect_to admin_reviews_path, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/_form.html.haml
.resume
	.avatar.pull-right.text-right
		= image_tag @review.avatar_url
	= render "resume", review: @review
.row
	.span4
		= simple_form_for(@review, url: admin_review_path(@review), html: {method: :put}) do |f|
			= f.error_notification
			.form-inputs
				= f.input :score
				= f.button :submit
	.span8
		%h3 Key
		%p Some kind of curriculum so we have a standard

app/views/admin/reviews/_resume.html.haml
= simple_form_for(review.resume, url: "#") do |f|
	.form-inputs
		= f.input :address, disabled: true
		= f.input :city, disabled: true
		= f.input :state, disabled: true
		= f.input :zipcode, disabled: true
		= f.input :phone_number, disabled: true
		= f.input :birthday, start_year: Date.today.year - 90, disabled: true

		= f.input :highest_education do
			= f.input_field :highest_education, label: "Curent Education (If applicable)",collection: ["High School", "College"], disabled: true
			= f.input_field :highest_major, placeholder: "Major (If applicable)", disabled: true

		= f.input :current_education do
			= f.input_field :current_education, label: "Curent Education (If applicable)",collection: ["High School", "College"], disabled: true
			= f.input_field :current_major, placeholder: "Major (If applicable)", disabled: true


		= f.input :graduation_date, start_year: Date.today.year - 90, disabled: true
		= f.input :description, input_html: { class: "span9", rows: 10 }, placeholder: "Tell us about yourself!", disabled: true
		%p Job Experience
		= f.simple_fields_for :job_experiences do |builder|
			.nested-fields
				= builder.input_field :title, label: false, placeholder: "Title", disabled: true
				= builder.input_field :company, label: false, placeholder: "Company", disabled: true
				= builder.input_field :time, label: false, as: :select, collection: time_frames_short, disabled: true


		%p References (3 Recommended)
		= f.simple_fields_for :references do |builder|
			.nested-fields
				= builder.input_field :name, label: false, placeholder: "Name", disabled: true
				= builder.input_field :relationship, label: false, placeholder: "Relationship", disabled: true
				= builder.input_field :length_known, label: false, placeholder: "Length Known", as: :select, collection: time_frames_long, disabled: true
				%br
				= builder.input_field :phone_number, label: false, placeholder: "Phone Number", disabled: true
				= builder.input_field :email, label: false, placeholder: "Email Address", disabled: true

app/views/admin/reviews/edit.html.haml
%h1= @review.full_name
= link_to 'Back', admin_reviews_path

= render 'form'

app/views/admin/reviews/index.html.haml
%h1 Review Some Users!!!!
%p.muted= "#{@reviews.count} employees to review"
%table
  %tr
    %th

  - @reviews.each do |review|
    %tr
      %td= link_to review.full_name, edit_admin_review_path(review)
%br