config/routes.rb
JobApp::Application.routes.draw do
  authenticated :user do
    root :to => 'marketing#employees'
  end
  root :to => 'marketing#employees'

  devise_for :users, skip: [:registrations]
  devise_for :employees, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}
  devise_for :employers, skip: [:sessions, :passwords], controllers: {registrations: 'registrations'}

  post "/avatar", to: "employees/resumes#avatar"
  namespace :employees do
  	resource :resume, only: ["edit", "update"]
    resources :applieds, only: ["create"]
  end
  resources :employees, only: ["show"]

  resources :listings, only: ["index", "show"]
  get '/employers', :to => 'marketing#employers'
  namespace :employers do
    get '/dashboard', to: 'dashboard#show', as: :dashboard
    get '/dashboard/potential_hires', to: 'potential_hires#index', as: :potential_hires
    resources :jobs, except: ['index', "show"]
  end


  #review namespace for ranking users
  namespace :admin do
    resources :reviews, only: ["index", "edit", "update"]
    resources :feedbacks, only: ['index']
    resources :stats, only: ['index']
  end

  get '/about_us', to: 'marketing#about_us'
  get '/contact', to: 'admin/feedbacks#new'
  post '/contact', to: 'admin/feedbacks#create'

  resources :charges, only: ['create']
end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController

	def employees

    if user_signed_in?
      flash.keep
  		redirect_to listings_path
    end

		@employee = Employee.new

    @coords = coords || Geocoder::BACKUP_LOCATION # Backup to nixa coords

    @near = near_formatted @coords
	end

  def employers
    @employer = Employer.new
  end

  def about_us
  end

  private

    def near_formatted coords
      n = Job.includes(:employer).near(coords, 20)
      return n.map do |near|
        {title: near.title, coords: [near.latitude, near.longitude],
          url: listing_path(near), company_name: near.employer.company_name}
      end
    end

    def coords
      if Rails.env.production?
        loc = request.location
        Geocoder.coordinates("#{loc.city}, #{loc.state}")
      else
        Geocoder.coordinates("Nixa, Missouri")
      end
    end

end

app/views/marketing/about_us.html.haml
%h1 About Us
.row
	.span12
		%p Everyone wants a summer job. JobPond is the result of three college students' less-than-successful quest for a summer job. As the applications piled up and the job offers didn't, we decided that someting needed to change. We had grown tired of writing the same name, address, job experience, and references for every application. So what did we do? We set out on a quest to make sure that no one else will ever have to do that again. The goal of JobPond is to create a Common Application for hourly jobs. JobPond let's job seekers fill out a single application and apply for every job with just the click of a button.

%h2 Meet the Team
%br
.row
	.span4
		=image_tag 'shane_profile.jpeg'
	.span8
		%h2 Shane Burkhart
		%p ADD PROFILE

%br

.row
	.span8
		%h2 Ryan Endacott
		%p ADD PROFILE
	.span4
		=image_tag 'ryan_profile.jpeg'

%br

.row
	.span4
		=image_tag 'daniel_profile.jpeg'
	.span8
		%h2 Daniel Holmgren
		%p Daniel is a sophomore at University of North Carolina studying Mathematics and Computer Science. When he isn't in the Dean Dome cheering for the Tar Heels, he stays busy with Mock Trial, Student Government, Sigma Phi Society, and, of course, programming
%br

app/views/marketing/employees.html.haml
- content_for(:no_container, true)
- content_for :tos_label do
	%span.text-black= "Accept"
	= link_to "Terms Of Service", "/tos.html", target: "_blank"

#map-heading-wrapper
	#map-canvas.absolute{data: {lat: @coords[0], long: @coords[1], near: @near.to_json}}

	#map-heading-promo-text.span6.well.border.higher
		%h2 Find Undergraduate Jobs!
		%p.lead Quickly and easily apply for tons of jobs with a single resume!
	#map-heading-sign-up.span4.well.border.higher
		%h2 Sign up
		= simple_form_for(@employee, url: employee_registration_path, html: {class: 'form-vertical' }) do |f|
			.row
				.span2
					= f.input_field :first_name, autofocus: true, placeholder: "First", class: "input-block-level"
				.span2
					= f.input_field :last_name, placeholder: "Last", class: "input-block-level"
			= f.input_field :email, placeholder: "Email", class: "input-block-level"
			= f.input_field :password, placeholder: "Password", class: "input-block-level"
			= f.input :accepted_tos, as: :boolean, inline_label: content_for(:tos_label), label: false
			= f.button :submit, 'Sign up', class: 'btn-primary btn-block btn-medium'
		%p.text-center
			Or
			= link_to "Sign In", new_user_session_path

.light-grey
	.container
		.row.learn-more
			.span4.offset4.text-center
				= link_to "Learn More", "#", class: "dark"

		.row
			.span12
				.row.marketing-section
					.span10
						%h2 Helping Undergraduates Find Jobs!
						%p.lead We want to make it quick and easy for high school and college students to find jobs.
					.span2
						%i.icon-search.icon-huge.text-warning

				.row.marketing-section
					.span2
						%i.icon-time.icon-huge.text-info
					.span10
						%h2 Stop Wasting Time - Find Jobs Quickly!
						%p.lead Don't waste anymore time searching for jobs.  Find available listings with a quick search.

				.row.marketing-section
					.span10
						%h2 No Degree Required!
						%p.lead Our primary goal is to find you jobs that don't require a college degree.
					.span2
						%i.icon-thumbs-up.icon-huge.text-success

				.row.marketing-section
					.span2
						%i.icon-check.icon-huge.text-error
					.span10
						%h2 One Click Applications
						%p.lead Apply for jobs with a single click!

				.row.marketing-section
					.span10
						%h2 Single Resume
						%p.lead One simple resume makes it quick and easy to apply for tons of jobs.
					.span2
						%i.icon-file.icon-huge.text-warning

		.row.back-to-top
			.span4.offset4.text-center
				= link_to "Back To Top", "#", class: "dark"

app/views/marketing/employers.html.haml
- content_for :no_container, true
- content_for :title, "Employer"
.hero-unit.dark
  .container
    .row
      .span12
        %h1 Find Quality Employees
        %br
        %p.lead We make finding quality employees fast and affordable!
        %p
          = link_to 'Sign up now!', new_employer_registration_path, class: 'btn btn-large btn-success'
.light-grey
  .container
    .row
      .span12
        .row.marketing-section
          .span2
            %i.icon-user.icon-huge.text-warning
          .span10
            %h2 Find Quality Applicants Fast With Our Employee Finder
            %p.lead Not only can job seekers find you, but you can look for them as well.  Our employee finder lets you easily find the highest qualified applicants.

        .row.marketing-section
          .span10
            %h2 Easily Manage Your Listings
            %p.lead Our employer dashboard makes it easy for you to manage and view all of your listings.
          .span2
            %i.icon-thumbs-up.icon-huge.text-info

        .row.marketing-section
          .span2
            %i.icon-time.icon-huge.text-error
          .span10
            %h2 Saving You Valuable Time
            %p.lead We know you have a lot to do.  Let us make it quickly and easily for you to post your listings.

        .row.marketing-section
          .span10
            %h2 Eliminate Paperwork
            %p.lead No one likes paperwork!  With JobPond.net, everything, from employee resumes to job listings, is electronic.
          .span2
            %i.icon-file.icon-huge.text-success